#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd -- "$(dirname -- "$0")" && pwd)
cd "$ROOT"

if [[ -z ${CXX:-} ]]; then
  if command -v g++ >/dev/null 2>&1; then
    CXX=g++
  else
    CXX=c++
  fi
fi
STD=${STD:-gnu++23}
CHECK_DIR=$(mktemp -d "${TMPDIR:-/tmp}/mt-folder-check.XXXXXX")
trap 'rm -rf "$CHECK_DIR"' EXIT

cargo fmt --check
cargo clippy --locked --all-targets -- -D warnings
cargo test --locked
cargo build --locked

MTF="$ROOT/target/debug/mtf"
"$MTF" sync
"$MTF" sync --check
"$MTF" render --target all --output-dir "$CHECK_DIR/book"
test -s "$CHECK_DIR/book/mtf.pdf"
test -s "$CHECK_DIR/book/index.html"
grep -q '>ModInt<' "$CHECK_DIR/book/index.html"
typst eval 'query(heading).map(it => it.body)' --in book.typ --root . \
  > "$CHECK_DIR/pdf-headings.json"
if grep -q 'ModInt' "$CHECK_DIR/pdf-headings.json"; then
  echo "PDF target unexpectedly contains the ModInt section" >&2
  exit 1
fi

HEADER_INDEX=0
mkdir -p "$CHECK_DIR/headers"
while IFS= read -r header; do
  include=${header#include/}
  printf '#include <%s>\nint main() {}\n' "$include" \
    > "$CHECK_DIR/headers/$HEADER_INDEX.cpp"
  ((HEADER_INDEX += 1))
done < <(find include/mtf -type f -name '*.hpp' | sort)
find "$CHECK_DIR/headers" -type f -name '*.cpp' -print0 \
  | xargs -0 -n 1 -P "${JOBS:-4}" "$CXX" -std="$STD" -Wall -Wextra \
      -Wno-reorder -Iinclude -fsyntax-only

CONTEST="$CHECK_DIR/contest"
mkdir -p "$CONTEST"
(
  cd "$CONTEST"
  "$MTF" init --compiler "$CXX" --std "$STD"
  "$MTF" new A
  "$MTF" compile A.cpp
  "$MTF" run A.cpp
)

cp examples/contest/A.cpp "$CONTEST/online.cpp"
(
  cd "$CONTEST"
  "$MTF" compile online.cpp
  "$MTF" bundle online.cpp > from-file.cpp
  "$MTF" bundle < online.cpp > from-stdin.cpp
  cmp from-file.cpp from-stdin.cpp
  "$MTF" check < from-file.cpp > checked.cpp
  cmp from-file.cpp checked.cpp

  if grep -Eq '^[[:space:]]*#[[:space:]]*include[[:space:]]*[<"]mtf/' \
    checked.cpp; then
    echo "bundled submission still contains an MTF include" >&2
    exit 1
  fi
  if grep -q 'Generated by mtf' checked.cpp; then
    echo "bundled submission contains a generator marker" >&2
    exit 1
  fi
  grep -q '^auto dijkstra' checked.cpp
  if grep -q '^struct DSU' checked.cpp; then
    echo "bundled submission contains an unused MTF module" >&2
    exit 1
  fi
  "$CXX" -std="$STD" -Wall -Wextra -Werror -fsyntax-only checked.cpp

  if printf 'int main( {' | "$MTF" check -o invalid.cpp 2> invalid.err; then
    echo "mtf check accepted invalid C++" >&2
    exit 1
  fi
  test ! -s invalid.cpp
  test -s invalid.err
)

cargo package --locked --allow-dirty --offline

echo "All checks passed"
