use std::collections::HashSet;
use std::ffi::OsString;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use anyhow::{Context, Result, bail};
use serde_json::Value;

use crate::cli::RenderTarget;
use crate::io_util::{absolute, atomic_write, find_parent_with};

pub const GENERATED_BANNER: &str = "// Generated by mtf. Edit the Typst sources instead.\n";
const ROOT_NAMESPACE: &str = "mtf";
const SNIPPET_QUERY: &str = "query(metadata).map(it => it.value)";
const EMBEDDED_SNIPPETS: &str = include_str!(concat!(env!("OUT_DIR"), "/mtf-snippets.json"));

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Header {
    pub path: String,
    pub content: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Starter {
    pub language: String,
    pub content: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Snapshot {
    pub headers: Vec<Header>,
    pub starters: Vec<Starter>,
}

impl Snapshot {
    pub fn starter(&self, language: &str) -> Result<&str> {
        self.starters
            .iter()
            .find(|starter| starter.language == language)
            .map(|starter| starter.content.as_str())
            .ok_or_else(|| anyhow::anyhow!("template snapshot has no {language} starter"))
    }
}

pub fn embedded_snapshot() -> Result<Snapshot> {
    snapshot_from_json(EMBEDDED_SNIPPETS)
        .context("the template snapshot embedded in mtf is invalid")
}

pub fn live_snapshot(root: &Path) -> Result<Snapshot> {
    let output = run_typst_capture(
        root,
        [
            OsString::from("eval"),
            OsString::from(SNIPPET_QUERY),
            OsString::from("--in"),
            OsString::from("book.typ"),
            OsString::from("--root"),
            root.as_os_str().to_owned(),
        ],
    )?;
    let json =
        String::from_utf8(output.stdout).context("Typst returned non-UTF-8 snippet metadata")?;
    snapshot_from_json(&json).context("Typst returned invalid snippet metadata")
}

pub fn snapshot_from_json(json: &str) -> Result<Snapshot> {
    let values: Vec<Value> =
        serde_json::from_str(json).context("snippet metadata must be a JSON array")?;
    let mut groups: Vec<(String, Vec<String>)> = Vec::new();
    let mut starters = Vec::new();

    for (index, value) in values.into_iter().enumerate() {
        let Some(object) = value.as_object() else {
            continue;
        };
        match object.get("kind").and_then(Value::as_str) {
            Some("mtf-snippet") => {
                let header = object
                    .get("header")
                    .and_then(Value::as_str)
                    .ok_or_else(|| anyhow::anyhow!("snippet {index} has no string header"))?;
                let code = object
                    .get("code")
                    .and_then(Value::as_str)
                    .ok_or_else(|| anyhow::anyhow!("snippet {index} has no string code"))?;
                validate_header_path(header)?;

                if let Some((_, chunks)) = groups.iter_mut().find(|(path, _)| path == header) {
                    chunks.push(code.to_owned());
                } else {
                    groups.push((header.to_owned(), vec![code.to_owned()]));
                }
            }
            Some("mtf-starter") => {
                let language = object
                    .get("language")
                    .and_then(Value::as_str)
                    .ok_or_else(|| anyhow::anyhow!("starter {index} has no string language"))?;
                let code = object
                    .get("code")
                    .and_then(Value::as_str)
                    .ok_or_else(|| anyhow::anyhow!("starter {index} has no string code"))?;
                if language.is_empty()
                    || language
                        .chars()
                        .any(|character| !(character.is_ascii_alphanumeric() || character == '-'))
                {
                    bail!("invalid starter language: {language}");
                }
                if starters
                    .iter()
                    .any(|starter: &Starter| starter.language == language)
                {
                    bail!("duplicate {language} starter");
                }
                starters.push(Starter {
                    language: language.to_owned(),
                    content: code.to_owned(),
                });
            }
            _ => continue,
        }
    }

    let prelude_index = groups
        .iter()
        .position(|(path, _)| path == "prelude.hpp")
        .ok_or_else(|| anyhow::anyhow!("Typst sources did not register prelude.hpp"))?;
    let (_, prelude_chunks) = groups.remove(prelude_index);
    let prelude = join_chunks(&prelude_chunks);
    let prelude = namespaced_body(&format!("using namespace std;\n\n{prelude}"));

    let mut headers = vec![Header {
        path: "prelude.hpp".to_owned(),
        content: format!("{GENERATED_BANNER}#pragma once\n\n#include <bits/stdc++.h>\n\n{prelude}"),
    }];

    let mut module_paths = Vec::new();
    for (path, chunks) in groups {
        let body = namespaced_body(&join_chunks(&chunks));
        headers.push(Header {
            path: path.clone(),
            content: format!(
                "{GENERATED_BANNER}#pragma once\n\n#include <mtf/prelude.hpp>\n\n{body}"
            ),
        });
        module_paths.push(path);
    }

    let mut all = String::from("#include <mtf/prelude.hpp>\n");
    for path in module_paths {
        all.push_str(&format!("#include <mtf/{path}>\n"));
    }
    headers.push(Header {
        path: "all.hpp".to_owned(),
        content: format!("{GENERATED_BANNER}#pragma once\n\n{all}"),
    });
    Ok(Snapshot { headers, starters })
}

fn join_chunks(chunks: &[String]) -> String {
    let mut body = chunks.join("\n");
    body.push('\n');
    body
}

fn namespaced_body(body: &str) -> String {
    format!("namespace {ROOT_NAMESPACE} {{\n\n{body}}}\n")
}

fn validate_header_path(path: &str) -> Result<()> {
    let parts: Vec<&str> = path.split('/').collect();
    if path.starts_with('/')
        || path.contains('\\')
        || !path.ends_with(".hpp")
        || parts
            .iter()
            .any(|part| part.is_empty() || *part == "." || *part == "..")
    {
        bail!("invalid generated header path: {path}");
    }
    if path == "all.hpp" {
        bail!("all.hpp is reserved for the generated umbrella header");
    }
    Ok(())
}

pub fn resolve_library_root(explicit: Option<&Path>) -> Result<PathBuf> {
    let root = match explicit {
        Some(path) => absolute(path)?,
        None => find_parent_with(
            &std::env::current_dir().context("cannot determine current directory")?,
            "book.typ",
        )?,
    };
    if !root.join("book.typ").is_file() || !root.join("template.typ").is_file() {
        bail!(
            "{} is not an MTF template library (book.typ/template.typ missing)",
            root.display()
        );
    }
    Ok(root)
}

pub fn sync_live(root: &Path, check: bool) -> Result<()> {
    let headers = live_snapshot(root)?.headers;
    let include_root = root.join("include/mtf");
    let changed = sync_header_set(&include_root, &headers, check)?;
    if !check && changed != 0 {
        eprintln!("updated {changed} generated header(s)");
    }
    Ok(())
}

pub fn sync_header_set(include_root: &Path, headers: &[Header], check: bool) -> Result<usize> {
    let mut stale = Vec::new();
    let expected: HashSet<PathBuf> = headers
        .iter()
        .map(|header| include_root.join(&header.path))
        .collect();

    for header in headers {
        let destination = include_root.join(&header.path);
        let current = match fs::read(&destination) {
            Ok(bytes) => Some(bytes),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
            Err(error) => {
                return Err(error).with_context(|| {
                    format!("cannot read generated header {}", destination.display())
                });
            }
        };
        if current.as_deref() != Some(header.content.as_bytes()) {
            stale.push(destination.clone());
            if !check {
                atomic_write(&destination, header.content.as_bytes())?;
            }
        }
    }

    let mut existing = Vec::new();
    collect_hpp(include_root, &mut existing)?;
    for path in existing {
        if expected.contains(&path) || !is_generated_header(&path)? {
            continue;
        }
        stale.push(path.clone());
        if !check {
            fs::remove_file(&path)
                .with_context(|| format!("cannot remove stale header {}", path.display()))?;
        }
    }

    if check && !stale.is_empty() {
        let names = stale
            .iter()
            .map(|path| format!("  {}", path.display()))
            .collect::<Vec<_>>()
            .join("\n");
        bail!("generated headers are stale; run `mtf sync`:\n{names}");
    }
    Ok(stale.len())
}

fn collect_hpp(directory: &Path, output: &mut Vec<PathBuf>) -> Result<()> {
    let entries = match fs::read_dir(directory) {
        Ok(entries) => entries,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(error) => {
            return Err(error)
                .with_context(|| format!("cannot read directory {}", directory.display()));
        }
    };
    for entry in entries {
        let entry = entry
            .with_context(|| format!("cannot read directory entry in {}", directory.display()))?;
        let path = entry.path();
        if path.is_dir() {
            collect_hpp(&path, output)?;
        } else if path.extension().and_then(|value| value.to_str()) == Some("hpp") {
            output.push(path);
        }
    }
    Ok(())
}

fn is_generated_header(path: &Path) -> Result<bool> {
    let bytes = fs::read(path)
        .with_context(|| format!("cannot inspect generated header {}", path.display()))?;
    let first_line = bytes
        .split(|byte| *byte == b'\n')
        .next()
        .unwrap_or_default();
    Ok(first_line.starts_with(b"// Generated by "))
}

pub fn render(root: &Path, target: RenderTarget, output_dir: &Path) -> Result<()> {
    sync_live(root, false)?;
    fs::create_dir_all(output_dir).with_context(|| {
        format!(
            "cannot create render output directory {}",
            output_dir.display()
        )
    })?;

    if matches!(target, RenderTarget::All | RenderTarget::Pdf) {
        let output = output_dir.join("mtf.pdf");
        run_typst(
            root,
            [
                OsString::from("compile"),
                OsString::from("book.typ"),
                output.as_os_str().to_owned(),
                OsString::from("--root"),
                root.as_os_str().to_owned(),
            ],
        )?;
        eprintln!("wrote {}", output.display());
    }

    if matches!(target, RenderTarget::All | RenderTarget::Html) {
        let output = output_dir.join("index.html");
        run_typst(
            root,
            [
                OsString::from("compile"),
                OsString::from("book.typ"),
                output.as_os_str().to_owned(),
                OsString::from("--root"),
                root.as_os_str().to_owned(),
                OsString::from("--features"),
                OsString::from("html"),
                OsString::from("--pretty"),
            ],
        )?;
        eprintln!("wrote {}", output.display());
    }
    Ok(())
}

fn typst_executable() -> OsString {
    std::env::var_os("MTF_TYPST").unwrap_or_else(|| OsString::from("typst"))
}

fn run_typst_capture<I>(root: &Path, arguments: I) -> Result<Output>
where
    I: IntoIterator<Item = OsString>,
{
    let output = Command::new(typst_executable())
        .current_dir(root)
        .args(arguments)
        .output()
        .context("cannot execute Typst; install typst-cli or set MTF_TYPST")?;
    if !output.status.success() {
        let detail = String::from_utf8_lossy(&output.stderr);
        bail!("Typst failed:\n{}", detail.trim_end());
    }
    Ok(output)
}

fn run_typst<I>(root: &Path, arguments: I) -> Result<()>
where
    I: IntoIterator<Item = OsString>,
{
    let status = Command::new(typst_executable())
        .current_dir(root)
        .args(arguments)
        .status()
        .context("cannot execute Typst; install typst-cli or set MTF_TYPST")?;
    if !status.success() {
        bail!("Typst failed with {status}");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn groups_multiple_chunks_in_document_order() {
        let json = r#"[
          {"kind":"mtf-snippet","header":"prelude.hpp","code":"using i64 = long long;"},
          {"kind":"mtf-starter","language":"cpp","code":"int main() {}"},
          {"kind":"mtf-snippet","header":"math/a.hpp","code":"int a;"},
          {"kind":"ignored"},
          {"kind":"mtf-snippet","header":"math/a.hpp","code":"int b;"}
        ]"#;
        let snapshot = snapshot_from_json(json).unwrap();
        let math = snapshot
            .headers
            .iter()
            .find(|header| header.path == "math/a.hpp")
            .unwrap();
        assert!(math.content.contains("int a;\nint b;\n"));
        assert!(math.content.contains("namespace mtf {"));
        let prelude = snapshot
            .headers
            .iter()
            .find(|header| header.path == "prelude.hpp")
            .unwrap();
        assert!(prelude.content.contains("namespace mtf {"));
        assert_eq!(snapshot.headers.last().unwrap().path, "all.hpp");
        assert_eq!(snapshot.starter("cpp").unwrap(), "int main() {}");
    }

    #[test]
    fn rejects_escaping_header_paths() {
        let json = r#"[
          {"kind":"mtf-snippet","header":"prelude.hpp","code":""},
          {"kind":"mtf-snippet","header":"../bad.hpp","code":""}
        ]"#;
        assert!(snapshot_from_json(json).is_err());
    }
}
